# Generated by Django 4.2.2 on 2023-06-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data_verifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfufileinfo',
            name='data_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
