# Generated by Django 4.2.2 on 2023-06-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data_verifier', '0002_dfufileinfo_data_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dfufileinfo',
            old_name='data_type',
            new_name='file_type',
        ),
    ]
