# Generated by Django 4.2.2 on 2023-06-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data_verifier', '0003_rename_data_type_dfufileinfo_file_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DFUFileInfo',
            new_name='DataFileInfo',
        ),
    ]
