# Generated by Django 4.2.2 on 2023-06-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data_verifier', '0004_rename_dfufileinfo_datafileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafileinfo',
            old_name='DFU_size_on_drive',
            new_name='Pictures_size_on_drive',
        ),
    ]
