# Generated by Django 4.2.3 on 2023-07-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data_verifier', '0005_rename_dfu_size_on_drive_datafileinfo_pictures_size_on_drive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafileinfo',
            name='file_hash',
        ),
    ]
