# Generated by Django 4.2.3 on 2023-07-11 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data_verifier', '0006_remove_datafileinfo_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientImageCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id_list', models.TextField(null=True)),
                ('image_count_list', models.TextField(null=True)),
                ('dataFileInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raw_data_verifier.datafileinfo')),
            ],
        ),
    ]
