# Generated by Django 4.2.3 on 2023-07-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data_verifier', '0007_patientimagecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafileinfo',
            name='PatientImageCountID',
            field=models.IntegerField(null=True),
        ),
    ]
