# Generated by Django 4.2.3 on 2023-07-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data_verifier', '0008_datafileinfo_patientimagecountid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafileinfo',
            old_name='data_transfer_time_range',
            new_name='data_acquisition_time_range',
        ),
    ]
