# Generated by Django 4.2.3 on 2023-07-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data_verifier', '0009_rename_data_transfer_time_range_datafileinfo_data_acquisition_time_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafileinfo',
            name='images_in_drive_without_overlap',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datafileinfo',
            name='images_in_excel_without_overlap',
            field=models.TextField(null=True),
        ),
    ]
