# Generated by Django 4.2.3 on 2023-07-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_data_verifier', '0011_rename_image_coll_count_in_drive_datafileinfo_image_coll_folder_count_in_drive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafileinfo',
            old_name='image_coll_folder_count_in_drive',
            new_name='image_coll_count_in_drive',
        ),
    ]
